### PR TITLE
Add ability to catch transactions included in future blocks

### PR DESCRIPTION
**Pull request by acoutts**
Credits to @Fletch153

### CODE REVIEW

**Comment by kesar** [comment]
nice catch 👍

**Review by kesar — APPROVED** [review]

**Comment by sim31** [comment]
Transactions which expire before ever being included in a block will now accumulate and will never be deleted from the action_queue. Maybe action_queue should be periodically checked for expired transactions now, so that memory could be freed?

**Comment by eosauthority** [comment]
Thanks @Fletch153 

@acoutts thanks for the PR - what do you think about the comment regarding freeing up expired transactions.

**Comment by acoutts** [comment]
That’s certainly a good point however I’m not sure how you could know whether or not a transaction is never going to make it to a block. While the memory leak would be slow, it’s definitely something to consider. 

I guess you have to weigh 2 things:
- how important is it that you never miss a single message related to your dapp.
- how much memory do you have to use.

**Comment by sim31** [comment]
Transactions have expiration field. You could use that to determine which transactions to clear. You would probably need to save it besides tx_id in the action_queue.

I'm not sure how common is the case that node is hit by a transaction which expires before being included in a block. I suspect it's quite rare. And if you occasionally restart the node, when upgrading it for example, then maybe this memory leak won't have any visible impact.

**Comment by eosauthority** [comment]
Merged and closed.

**Pull request merged**
